graph TD
subgraph Genesis
i1(Input) --> o1(Output)
end

subgraph Block A
i2(Input) --> o2(Output)
o1 --> i2
i2 --> o3(Unspent Output)
end

subgraph Block B
i3(Input) --> o4(Unspent  Output)
o2 --> i3
i3 --> o5(Unspent Output)
end